/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdjustLine: typeof import('./src/components/AdjustLine.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor/code-editor.vue')['default']
    IconFluentCollections24Regular: typeof import('~icons/fluent/collections24-regular')['default']
    IconHugeiconsInbox: typeof import('~icons/hugeicons/inbox')['default']
    IconMynauiTrash: typeof import('~icons/mynaui/trash')['default']
    IconSolarHome2Outline: typeof import('~icons/solar/home2-outline')['default']
    'IconStash:arrowReplyDuotone': typeof import('~icons/stash/arrow-reply-duotone')['default']
    NavBar: typeof import('./src/ui/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
