/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdjustLine: typeof import('./src/components/AdjustLine.vue')['default']
    Card: typeof import('./src/components/Card/Card.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor/code-editor.vue')['default']
    CodeEditorPlus: typeof import('./src/components/CodeEditor/code-editor-plus.vue')['default']
    'IconBxs:error': typeof import('~icons/bxs/error')['default']
    'IconGrommetIcons:update': typeof import('~icons/grommet-icons/update')['default']
    'IconIx:reset': typeof import('~icons/ix/reset')['default']
    'IconMaterialSymbols:save': typeof import('~icons/material-symbols/save')['default']
    'IconStash:arrowReplyDuotone': typeof import('~icons/stash/arrow-reply-duotone')['default']
    NavBar: typeof import('./src/ui/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Update: typeof import('./src/ui/Update.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
